name: Regression End-to-end tests

on: 
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build  # optional: only if your app requires a build step
          start: npm start      # optional: only if your app requires a dev server
